src/account/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from account.views import user_login, user_profile, user_signup

app_name = "account"

urlpatterns = [
    path("profile/", user_profile, name="profile"),
    path("signup/", user_signup, name="signup"),
    path("login/", user_login, name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

src/blog/urls.py
from django.urls import path

from blog.views import (
    PostListByTagView,
    PostListByUserView,
    PostListView,
    post_comment,
    post_detail,
    post_share,
)

app_name = "blog"

urlpatterns = [
    path(
        "posts/<int:year>/<int:month>/<int:day>/<slug:slug>",
        post_detail,
        name="post_detail",
    ),
    path("posts/<int:post_id>/comment/", post_comment, name="post_comment"),
    path("posts/<int:post_id>/share/", post_share, name="post_share"),
    path(
        "posts/tag/<slug:tag_slug>", PostListByTagView.as_view(), name="post_list_by_tag"
    ),
    path("posts/<username>", PostListByUserView.as_view(), name="post_list_by_user"),
    path("posts/", PostListView.as_view(), name="post_list"),
]

src/django_blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .api import api

urlpatterns = [
    path("api/", api.urls),
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
    path("", include("blog.urls", namespace="blog")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      Мой блог{% block title %}
      {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/daisyui@4.7.0/dist/full.min.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'css/global.css' %}" />
    {% block css %}

    {% endblock %}
  </head>
  <body>
    <heaedr class="header">
      {% include "./nav.html"%}
    </heaedr>
    <main class="flex flex-col gap-8 p-4 main">
      {% block main %}

      {% endblock %}
    </main>
    <footer class="footer"></footer>
    {% block js %}

    {% endblock %}
  </body>
</html>

src/templates/nav.html
<nav class="navbar bg-base-100">
  <div class="flex-1">
    <a href="{% url 'blog:post_list' %}" class="btn btn-ghost text-xl">B Log</a>
    <ul class="menu menu-sm menu-horizontal p-2">
      <li>
        <a href="{% url 'blog:post_list' %}">Feed</a>
      </li>
      <li>
        <a href="{% url 'blog:post_list' %}">All Posts</a>
      </li>
      {% if request.user.is_authenticated %}
      <li>
        <a href="/posts/{{request.user.username}}">My Posts</a>
      </li>
      {% endif %}
    </ul>
  </div>
  <div class="flex-none gap-2">
    <div class="form-control">
      <input type="text" placeholder="Search" class="input input-bordered w-24 md:w-auto" />
    </div>
    {% if request.user.is_authenticated %}
    <div class="dropdown dropdown-end">
      <div tabindex="0" role="button" class="btn btn-ghost btn-circle avatar">
        <div class="w-10 rounded-full">
          <img alt="user avatar" src="{{ request.user.profile.avatar.url }}" />
        </div>
      </div>
      <ul tabindex="0" class="mt-3 z-[1] p-2 shadow menu menu-sm dropdown-content bg-base-100 rounded-box w-52">
        <li>
          <a href="{% url 'account:profile' %}" class="justify-between">
            Profile
            <span class="badge">{{request.user.username}}</span>
          </a>
        </li>
        <li>
          <a>Settings</a>
        </li>
        <li>
            <form action="{% url 'account:logout' %}" method="post">
                {% csrf_token %}
                <input class="cursor-pointer"type="submit" value="Log Out">
            </form>
        </li>
      </ul>
    </div>
    {% else %}
    <div class="ml-auto">
        <a class="justify-end" href="{% url 'account:login' %}">Log In</a>
    </div>
    {% endif %}
  </div>
</nav>