src/blog/urls.py
from django.urls import path

from blog.views import (
    PostListByTagView,
    PostListByUserView,
    PostListView,
    post_comment,
    post_detail,
    post_share,
)

app_name = "blog"

urlpatterns = [
    path(
        "posts/<int:year>/<int:month>/<int:day>/<slug:slug>",
        post_detail,
        name="post_detail",
    ),
    path("posts/<int:post_id>/comment/", post_comment, name="post_comment"),
    path("posts/<int:post_id>/share/", post_share, name="post_share"),
    path(
        "posts/tag/<slug:tag_slug>", PostListByTagView.as_view(), name="post_list_by_tag"
    ),
    path("posts/<username>", PostListByUserView.as_view(), name="post_list_by_user"),
    path("posts/", PostListView.as_view(), name="post_list"),
]

src/django_blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .api import api

urlpatterns = [
    path("api/", api.urls),
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
    path("", include("blog.urls", namespace="blog")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager

from blog.manager import PublishedManeger


class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = "DRAFT", "Draft"
        PUBLISHED = "PUB", "Published"

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=100, unique_for_date="published")
    body = models.TextField()
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.DRAFT)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")

    published = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    tags = TaggableManager()

    objects = models.Manager()
    approved = PublishedManeger()

    class Meta:
        ordering = ["-published"]
        indexes = [models.Index(fields=["-published"])]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "blog:post_detail",
            args=[
                self.published.year,
                self.published.month,
                self.published.day,
                self.slug,
            ],
        )


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")
    body = models.TextField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created"]
        indexes = [models.Index(fields=["-created"])]

    def __str__(self):
        return f"Comment by {self.user} on {self.post}"

src/blog/forms.py
from django import forms

from blog.models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "slug", "body"]


class EmailPostForm(forms.Form):
    username = forms.CharField(max_length=50)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(widget=forms.Textarea, required=False)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["body"]

src/blog/views.py
from typing import Any

from django.conf import settings
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.db.models.query import QuerySet
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.views.decorators.http import require_POST
from django.views.generic import ListView
from taggit.models import Tag

from blog.forms import CommentForm, EmailPostForm, PostForm
from blog.models import Post


class PostListView(ListView):
    queryset = Post.approved.all()
    paginate_by = 5
    context_object_name = "posts"
    template_name = "blog/post/list.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["new_form"] = PostForm()
        return context


class PostListByUserView(ListView):
    paginate_by = 5
    context_object_name = "posts"
    template_name = "blog/post/list.html"

    def get_queryset(self) -> QuerySet[Any]:
        username = self.kwargs.get("username")
        queryset = Post.objects.filter(author__username=username)

        return queryset


class PostListByTagView(ListView):
    paginate_by = 5
    context_object_name = "posts"
    template_name = "blog/post/list.html"

    def get_queryset(self) -> QuerySet[Any]:
        tag_slug = self.kwargs.get("tag_slug")
        tag = get_object_or_404(Tag, slug=tag_slug)
        queryset = Post.approved.filter(tags__in=[tag])
        return queryset


@require_POST
def post_comment(request, post_id):
    try:
        post = Post.approved.get(id=post_id)
    except Post.DoesNotExist:
        raise Http404("No post found")

    comment = None
    form = CommentForm(request.POST)

    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.user = User.objects.get(id=1)
        comment.save()

    return render(
        request,
        "blog/post/comment.html",
        {"post": post, "form": form, "comment": comment},
    )


def post_detail(request, year, month, day, slug):
    try:
        post = Post.approved.filter(
            published__year=year, published__month=month, published__day=day, slug=slug
        ).get()
    except Post.DoesNotExist:
        raise Http404("No post found")

    return render(
        request,
        "blog/post/detail.html",
        {"post": post, "comments": post.comments.all(), "form": CommentForm()},
    )


def post_share(request, post_id):
    try:
        post = Post.approved.get(id=post_id)
    except Post.DoesNotExist:
        raise Http404("No post found")

    if request.method == "GET":
        return render(
            request,
            "blog/post/share.html",
            {"post": post, "form": EmailPostForm(), "sent": False},
        )

    form = EmailPostForm(request.POST)
    sent = False

    if form.is_valid():
        cd = form.cleaned_data
        post_url = request.build_absolute_uri(post.get_absolute_url())
        subject = f"{cd['username']} recommends you read {post.title}"
        message = (
            f"Read {post.title} at {post_url}\n\n"
            f"{cd['username']}'s comments: {cd['comments']}"
        )
        print(subject, message, settings.EMAIL_HOST_USER, [cd["to"]])
        send_mail(subject, message, settings.EMAIL_HOST_USER, [cd["to"]])
        sent = True

    return render(
        request,
        "blog/post/share.html",
        {"post": post, "form": form, "sent": sent},
    )

src/templates/blog/post/comment_form.html
{% load render_markdown %}
{% load forms_tags %}

<div class="collapse bg-base-200">
    <input type="checkbox" />
    <div class="collapse-title text-xl font-medium">
        Add a new comment
    </div>
    <div class="collapse-content">
        <form action="" method="post" class="flex flex-col gap-2 mt-4">
                <input type="number" value="{{ post.id }}" name="post_id" hidden>
                {{ form.body|with_class:'textarea textarea-bordered resize-none w-full'}}

            {% csrf_token %}
            <button class="btn btn-outline btn-primary self-end mt-2" type="submit">Send</button>
          </form>
    </div>
  </div>

src/templates/blog/post/detail.html
{% extends 'base.html' %}

{% block title %}
  : Читать
{% endblock %} {% block main %}
  <h2 class="main__heading text-4xl">{{ post.title }}</h2>

  <article class="post">
    <p class="post__body text-xl">{{ post.body }}</p>
    <footer class="post__meta mt-4">Published {{ post.published }} by {{ post.author }}
      <a class="btn btn-sm btn-outline btn-secobdary ml-2" href="{% url "blog:post_share"  post.id %}">Share</a>
    </footer>
  </article>

{% comment %} {% with comments.count as total_comments %}
    <h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
  {% endwith %}
  {% for comment in comments %}
    <div class="comment">
      <p class="info">Comment {{ forloop.counter }} by {{ comment.user_id }}
        {{ comment.created }}</p>
      {{ comment.body|linebreaks }}
    </div>
    {% empty %}
    <p>There are no comments.</p>
  {% endfor %} {% endcomment %}

  <section class="comments">
    <h2 class="comments__counter"></h2>
    <div class="comments__content"></div>
  </section>

  {% include "blog/post/comment_form.html" %}
{% endblock %}


{% block js %}
<script>
  function createCommentElement({ body, created, user}) {
    const commentElement = document.createElement("div")
    commentElement.innerHTML = `<div class="comment">
      <p class="info">Comment by ${user.username} ${new Date(created).toLocaleString("ru")} </p>
        ${body}
    </div>`

    return commentElement
  }

  function loadComments() {
    fetch("/api/blog/comments/{{ post.id }}").then(responce => {
      if (!responce.ok) {
        throw new Error("API Error")
      }
      return responce.json()
    }).then(data => {
      if (data.length === 0) {
        commentsCounter.textContent = "There are no comments yet..."
      } else {
        commentsCounter.textContent = `There are ${data.length} comments`
      }
      commentsContent.innerHTML = '<div class="comments__content"></div>'
      commentsContent.append(...data.map(createCommentElement))
    })
    .catch(error => {
      console.error(error)
    })
  }


  function handleSubmit(event) {
    event.preventDefault()
    const formData = newForm.elements
    const post_id = +formData["post_id"].value
    const body = formData["body"].value

    fetch("/api/blog/comments/", {
      method: "post",
      body: JSON.stringify({ post_id, body }),
      headers: {
        "Content-Type": "application/json"
      }
    }).then((responce) => {
      if (!responce.ok) {
        throw new Error("API error")
      }
      loadComments()
      formData["body"].value = ""
    })
    .catch(error => console.log(error))
  }

  const newForm = document.querySelector(".collapse form[method=post]")
  const commentsCounter = document.querySelector(".comments__counter")
  const commentsContent = document.querySelector(".comments__content")

  newForm.addEventListener("submit", handleSubmit)
  document.addEventListener("DOMContentLoaded", loadComments)
</script>

{% endblock%}

src/templates/blog/post/list.html
{% extends 'base.html' %}

{% block tiitle %}
  : Все статьи
{% endblock %}

{% load render_markdown %}
{% load forms_tags %}

{% block main %}
  <h2 class="text-2xl">All Posts</h2>

{% if request.user.is_authenticated  %}
<button class="btn fixed z-10 bottom-2 right-10 btn-warning text-fuchsia-800 outline-hidden" onclick="new_post.showModal()">New Post</button>
{% endif %}

<dialog id="new_post" class="modal">
  <div class="modal-box">
    <form method="dialog">
      <button class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2">✕</button>
    </form>
    <h3 class="font-bold text-lg">Create a new post</h3>
    <form action="" method="post" class="flex flex-col gap-2 mt-8">
      <label for="title" class="label-text">{{ new_form.title.label }}</label>
        {{ new_form.title|with_class:'input input-bordered w-full'}}

      <label for="body" class="label-text">{{ new_form.body.label }}</label>
        {{ new_form.body|with_class:'textarea textarea-bordered resize-none w-full'}}

      {% csrf_token %}
      <button class="btn btn-outline btn-primary self-end" type="submit">Create</button>
    </form>
  </div>
</dialog>

  {% for post in posts %}
    <article class="card card-side bg-base-100 shadow-xl post">
      <figure class="shrink-0"><img src="https://daisyui.com/images/stock/photo-1635805737707-575885ab0820.jpg" alt="avatar"/></figure>
      <div class="card-body">
        <header class="p-8 flex gap-2">
          Теги:
          {% for tag in post.tags.all %}
          <a href="{% url 'blog:post_list_by_tag' tag.slug %}" class="badge badge-primary cursor-pointer">{{ tag }}</a>
          {% endfor %}
        </header>
        <h3 class="card-title">
          <a href="{{ post.get_absolute_url }}" class="post__link">
            {{ post.title }}
          </a>
        </h3>
        <p class="text-lg">{{ post.body|render_markdown|truncatewords:30 }}</p>
        <footer class="text-base">Published {{ post.published }} by {{ post.author }}</footer>
      </div>
    </article>
    {% empty%}
    <p class="text-lg">Sorry. You have not posts yet. Wanna write your first post? </p>
  {% endfor %}
  {% include "blog/post/pagination.html" with page=page_obj %}
{% endblock %}

{% block js %}
<script>
  function handleSubmit(event) {
    event.preventDefault()
    const formData = newForm.elements
    const title = formData["title"].value
    const body = formData["body"].value

    fetch("/api/blog/", {
      method: "post",
      body: JSON.stringify({title, body}),
      headers: {
        "Content-Type": "application/json"
      }
    }).then((responce) => {
      if (!responce.ok) {
        throw new Error("API error")
      }
      location.reload()
    })
    .catch(error => console.log(error))
  }

  const newForm = document.querySelector(".modal form[method=post]")

  newForm.addEventListener("submit", handleSubmit)
</script>

{% endblock%}

src/templates/blog/post/pagination.html
{% if page.paginator.num_pages > 1 %}
<div class="join pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <aclass="join-item btn"  href="?page={{ page.previous_page_number }}">«Previous»</a>
    {% endif %}
    <span class="join-item btn btn-primary" class="current">Page {{ page.number }} of {{ page.paginator.num_pages }}</span>
    {% if page.has_next %}
      <a class="join-item btn" href="?page={{ page.next_page_number }}">«Next»</a>
    {% endif %}
  </span>
</div>
{% endif%}

src/templates/blog/post/share.html
{% extends 'base.html' %}

{% block title %}
  Share a post
{% endblock %}

{% block main %}
  {% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>"{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.</p>
  {% else %}
    <h1>Share "{{ post.title }}" by e-mail</h1>
    <form method="post" novalidate>
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Send e-mail" />
    </form>
  {% endif %}
{% endblock %}